### PR TITLE
rdb to firestore db

### PR DESCRIPTION
**Pull request by LourenzBani**

### CODE REVIEW

**Comment by Aspyse** [comment]
_I apologize if this feels like extra work, but we are working as a team, so we must put in the effort to write maintainable and readable code._
### Resolve before merging
- `main.js` and `main.css` must be loaded in every route. This way, we can track and use global behaviors and values in the project.
    - Conversely, please only use these files for GLOBAL behaviors and values. Migrate the rules in `main.css` that are NOT loaded on every page. Put these in their individual CSS files and load these after `main.css`.
- Do not write JS inline in the HBS files.
    - Specifically, please remove the inline JS in `login.hbs` and put it in its own JS file. You can then pass this to the `scripts` parameter in the routes.
- Centralize the Firebase imports and config into one JS module. Call this module from whichever JS files need to use it. See [this file](https://github.com/Aspyse/research-support-hub/blob/30be2645a18d3b799656668105cad21b93519540/server/firebase.js).
### Issues from previous pull request
Sorry, I missed these when I reviewed the previous PR. Please resolve them in this one, instead.
- Revert `index.hbs` to [this version](https://github.com/Aspyse/research-support-hub/blob/30be2645a18d3b799656668105cad21b93519540/views/layouts/index.hbs).
    - It is a template that keeps us from writing duplicate code such as the `<!DOCTYPE html>`.
    - Use handlebars to fill in the details that vary between pages, such as the title.
    - If the template is genuinely insufficient, create another template in `views/layouts`.
- `header.hbs` is incorrectly formatted for a partial. It should ONLY contain the header segment to be reused in different pages.

**Comment by LourenzBani** [comment]
No worries, I will adjust them accordingly.

**Comment by LourenzBani** [comment]
anyone know how to fix this error?
image
I'm trying to use the firebase.js but for some reason it keeps saying that whenever I call it in the register.js.
firebase.js problem:
image
register.js import:
image

**Comment by LourenzBani** [comment]
image
this was the workaround I found from searching google. I just used the cdn links instead

**Comment by Aspyse** [comment]
> image this was the workaround I found from searching google. I just used the cdn links instead

Yes, you have to use CDN links for client-side JS because we are not bundling.

**Comment by LourenzBani** [comment]
okay ty, I've cleaned up the hbs and also connected the js to the firebase.js

**Pull request closed without merging**
